### ISSUE TITLE
Should users be able to change colors?

### ISSUE THREAD

**Issue by kyle-jennings** [LavertyCreative/The-Standards#2]
This is just a philosophical issue, but should the users be able to change the site colors?  Seems like one of the big sells of the USWDS is having this pre-styled theme that looks good as is.   Once you open up the customizer to change colors the site quickly just becomes bootstrap with funky colors.

Maybe the customizer should be limited to branding and layout settings?

**Comment by lavekyl** [comment]
I added the option to change colors because there are multiple colors to choose from within the standards. I guess I could have narrowed it down to those, but I wanted to leave it open. I've seen some of the sites using different colors that also use the standards also.
